# Exclude test fixtures from secret scanning
# These files contain fake API keys used for testing the redaction system
paths-ignore:
  - "internal/safety/redaction/redaction_test.go"
  - "docs/REDACTION_SPEC.md"
  - "testdata/redaction_fixtures.json"
